import { editor } from 'monaco-editor';

export const vibeDarkTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'c678dd' },
    { token: 'number', foreground: 'd19a66' },
    { token: 'string', foreground: '98c379' },
    { token: 'operator', foreground: '56b6c2' },
    { token: 'identifier', foreground: 'abb2bf' },
    { token: 'type.identifier', foreground: 'e5c07b' },
    { token: 'delimiter', foreground: 'abb2bf' },
    { token: 'tag', foreground: 'e06c75' },
    { token: 'attribute.name', foreground: 'd19a66' },
    { token: 'attribute.value', foreground: '98c379' },
    { token: 'string.escape', foreground: '56b6c2' },
    { token: 'predefined', foreground: 'e5c07b' },
  ],
  colors: {
    'editor.background': '#00000000',
    'editorGutter.background': '#00000000',
    'editor.foreground': '#ABB2BF',
    'editor.inactiveSelectionBackground': '#3a3d41',
    'editor.selectionBackground': '#44475A',
    'editor.selectionHighlightBackground': '#44475A80',
    'editorCursor.foreground': '#C7D2FE',
    'editorLineNumber.foreground': '#4B5563',
    'editorLineNumber.activeForeground': '#C7D2FE',
    'editorHoverWidget.background': '#1A1A22',
    'editorHoverWidget.border': '#2A2A33',
    'editorSuggestWidget.background': '#1A1A22',
    'editorSuggestWidget.border': '#2A2A33',
    'editorSuggestWidget.selectedBackground': '#2C313A',
    'editorBracketMatch.background': '#2C313A',
    'editorBracketMatch.border': '#4B5563',
  }
};

export const vibeLightTheme: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '939cb0', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'be43d4' },
    { token: 'number', foreground: 'd19a66' },
    { token: 'string', foreground: '1d7d32' },
    { token: 'operator', foreground: '098658' },
    { token: 'identifier', foreground: '2d3142' },
    { token: 'type.identifier', foreground: 'c18401' },
    { token: 'delimiter', foreground: '383a42' },
    { token: 'tag', foreground: 'd73a49' },
    { token: 'attribute.name', foreground: '6f42c1' },
    { token: 'attribute.value', foreground: '032f62' },
    { token: 'string.escape', foreground: '22a069' },
    { token: 'predefined', foreground: 'c18401' },
  ],
  colors: {
    'editor.background': '#00000000',
    'editorGutter.background': '#00000000',
    'editor.foreground': '#1C2130',
    'editor.inactiveSelectionBackground': '#E0E3E9',
    'editor.selectionBackground': '#BDD5F3',
    'editor.selectionHighlightBackground': '#BDD5F380',
    'editorCursor.foreground': '#1D4ED8',
    'editorLineNumber.foreground': '#A1A8BD',
    'editorLineNumber.activeForeground': '#1D4ED8',
    'editorHoverWidget.background': '#F1F5F9',
    'editorHoverWidget.border': '#E2E8F0',
    'editorSuggestWidget.background': '#F1F5F9',
    'editorSuggestWidget.border': '#E2E8F0',
    'editorSuggestWidget.selectedBackground': '#E0E3E9',
    'editorBracketMatch.background': '#D2D8E7',
    'editorBracketMatch.border': 'transparent',
  }
};